### ISSUE TITLE
Guardar Socio

### ISSUE THREAD

**Issue by FacuSautu** [brunogitsistemas/DataSocios#5]
Luego de cargar los datos y apretar el botón de ingresar te redirecciona a la pagina de inicio, en mi opinión seria mejor que guarde el usuario, mantenga la pagina de Nuevo Socio y te limpie los campos, por si se desea agregar un nuevo Usuario.

**Comment by brunogitsistemas** [comment]
Aun no tenemos redireccionado el botón de "GUARDAR SOCIO" a una Base de Datos. Falta hacer el aviso para "Cancelar" "Confirmar"
